language: java

jdk:
  - openjdk8
  - openjdk11

# for more details see the following link
# https://docs.travis-ci.com/user/sonarcloud/#inspecting-code-with-the-sonarqube-scanner
addons:
  sonarcloud:
    organization: "cookiemr-github"

script:
  - sonar-scanner
